baseURL = "https://stahl-scott.firebaseapp.com"
languageCode = "en-us"
title = "Scott Stahl"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

[params]
    author = "Scott Stahl"
    description = "Developer & team builder"
    githubUsername = "stahlscott"
    accent = "gray"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["python", "react"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:stahl.scott@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/stahlscott/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/stahlish/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/stahlscott/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/story/5495645"
    name = "stack-overflow"
    weight = 5
